[package]
name = "reflink"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["ioapiset", "winioctl", "fileapi"] }
